# Generated by Django 3.2.16 on 2024-09-11 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
