# Generated by Django 3.2.16 on 2024-09-12 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('distant', models.IntegerField()),
                ('description', models.CharField(max_length=120)),
            ],
        ),
    ]
